# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

strategy:
  matrix:
    MacOS:
      imageName: 'macOS-latest'
    Linux:
      imageName: 'ubuntu-latest'
    Windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

variables:
  buildConfiguration: 'Release'

steps:

# install NuGet
- task: NuGetToolInstaller@0
  displayName: 'Install NuGet'

# automatically install packages noted in the solution
- task: NuGetCommand@2
  displayName: 'NuGet Restore Packages'
  inputs:
    restoreSolution: 'src/ScottPlotNoGUI.sln'

# build ScottPlot (not the user controls)
- task: DotNetCoreCLI@2
  displayName: 'Build ScottPlot and Tests'
  inputs:
    packageType: 'sdk'
    command: 'build'
    projects: |
     src/ScottPlot/ScottPlot.csproj 
     tests/ScottPlotTests.csproj

# test ScottPlot (not the user controls)
- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: test
    projects: 'tests/ScottPlotTests.csproj'

# NuGet restore all packages (including GUI stuff) if using Windows
- task: NuGetCommand@2
  displayName: 'NuGet Restore Full Solution'
  condition: contains(imageName, 'windows')
  inputs:
    restoreSolution: 'src/ScottPlot.sln'

# Build the entire solution (user controls and demos) if using Windows
- task: VSBuild@1
  displayName: 'Build Full Solution'
  condition: contains(imageName, 'windows')
  inputs:
    solution: 'src/ScottPlot.sln'
