trigger:
- master

strategy:
  matrix:
    MacOS:
      imageName: 'macOS-latest'
    Linux:
      imageName: 'ubuntu-latest'
    Windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

variables:
  buildConfiguration: 'Release'

steps:

- task: NuGetToolInstaller@0
  displayName: 'Install NuGet'
    
- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    projects: 'src/ScottPlot.sln'
    
- task: DotNetCoreCLI@2
  displayName: 'Build ScottPlot'
  inputs:
    command: 'build'
    projects: src/ScottPlot/ScottPlot.csproj

- task: DotNetCoreCLI@2
  displayName: 'Build Tests'
  inputs:
    command: 'build'
    projects: tests/ScottPlotTests.csproj
     
- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: test
    projects: 'tests/ScottPlotTests.csproj'
     
### If on Windows, build the entire solution

- script: dotnet restore
  displayName: 'Restore (Windows only)'
  condition: contains(variables['agent.os'], 'Windows')

- task: VSBuild@1
  displayName: 'Build full solution (Windows only)'
  condition: contains(variables['agent.os'], 'Windows')
  inputs:
    clear: true
    projects: 'src/ScottPlot.sln'