trigger:
- master

strategy:
  matrix:
    MacOS:
      imageName: 'macOS-latest'
    Linux:
      imageName: 'ubuntu-latest'
    Windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

variables:
  buildConfiguration: 'Release'

steps:

### INSTALL NUGET

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

### LIMITED RESTORE AND BUILD (MacOS and Linux)

- task: NuGetCommand@2
  displayName: 'Limited package restoration'
  condition: not(contains(variables['agent.os'], 'Windows'))
  inputs:
    restoreSolution: 'src/ScottPlotNoGUI.sln'
    
- task: DotNetCoreCLI@2
  displayName: 'Limited build'
  condition: not(contains(variables['agent.os'], 'Windows'))
  inputs:
    command: 'build'
    projects: 'src/ScottPlotNoGUI.sln'
    
### FULL RESTORE AND BUILD (Windows)

- task: NuGetCommand@2
  displayName: 'Full package restoration'
  condition: contains(variables['agent.os'], 'Windows')
  inputs:
    restoreSolution: 'src/ScottPlot.sln'
    
- task: VSBuild@1
  displayName: 'Full build'
  condition: contains(variables['agent.os'], 'Windows')
  inputs:
    projects: 'src/ScottPlot.sln'
    
### RUN TESTS

- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: test
    projects: 'tests/ScottPlotTests.csproj'
