trigger:
- master

strategy:
  matrix:
    FormatChecker:
      poolName: 'Autoformat Checker'
      imageName: 'ubuntu-latest'
    MacOS:
      poolName: 'MacOS Build and Test'
      imageName: 'macOS-latest'
    Linux:
      poolName: 'Linux Build and Test'
      imageName: 'ubuntu-latest'
    Windows:
      poolName: 'Linux Build and Test'
      imageName: 'windows-latest'

pool:
  name: $(poolName)
  vmImage: $(imageName)

steps:

### GET OLDEST .NET CORE 2 (FOR TESTS)
- task: UseDotNet@2
  displayName: 'Acquire .NET Core 2.0.0'
  inputs:
    packageType: 'sdk'
    version: '2.0.0'

### GET LATEST .NET CORE 3 (FOR TOOLS)
- task: UseDotNet@2
  displayName: 'Acquire .NET Core 3'
  inputs:
    packageType: 'sdk'
    version: '3.x'

### INSTALL DOTNET FORMAT
- task: DotNetCoreCLI@2
  displayName: 'Install dotnet-format'
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'update -g dotnet-format'

### FAIL IF AUTOFORMATTING IS REQUIRED
- task: DotNetCoreCLI@2
  displayName: 'Check Formatting'
  condition: eq(variables['poolName'], 'Autoformat Checker')
  inputs:
    command: 'custom'
    custom: 'format'
    arguments: '-w src/ScottPlotV4.sln --dry-run --check --verbosity diagnostic'

### INSTALL NUGET AND RESTORE PACKAGES

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: NuGetCommand@2
  displayName: 'Full package restoration'
  inputs:
    restoreSolution: 'src/ScottPlotV4.sln'

### BUILD SCOTTPLOT AND DEMO

- task: DotNetCoreCLI@2
  displayName: 'Build ScottPlot'
  inputs:
    command: 'build'
    projects: 'src/ScottPlot/ScottPlot.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build ScottPlot.Demo'
  inputs:
    command: 'build'
    projects: 'src/ScottPlot.Demo/ScottPlot.Demo.csproj'

### BUILD AND RUN TESTS
- task: DotNetCoreCLI@2
  displayName: 'Build Tests'
  inputs:
    command: 'build'
    projects: 'tests/ScottPlotTests.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: test
    projects: 'tests/ScottPlotTests.csproj'

### BUILD RELEASE OF FULL SOLUTION (Windows only)
    
- task: VSBuild@1
  displayName: 'Build Release (Windows)'
  condition: contains(variables['agent.os'], 'Windows')
  inputs:
    solution: 'src/ScottPlotV4.sln'
    configuration: 'release'