trigger:
- master

strategy:
  matrix:
    MacOS:
      imageName: 'macOS-latest'
    Linux:
      imageName: 'ubuntu-latest'
    Windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
    
### INSTALL DOTNET FORMAT
- task: DotNetCoreCLI@2
  displayName: 'Install dotnet-format'
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'update -g dotnet-format'

### FAIL IF AUTOFORMATTING IS REQUIRED
- task: CmdLine@2
  inputs:
    script: 'dotnet format -w src/ScottPlotV4.sln --dry-run --check --verbosity diagnostic' 

### INSTALL NUGET AND RESTORE PACKAGES

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: NuGetCommand@2
  displayName: 'Full package restoration'
  inputs:
    restoreSolution: 'src/ScottPlotV4.sln'

### BUILD AND PACK PACKAGES THAT WORK ON EVERY OS

- task: DotNetCoreCLI@2
  displayName: 'Build ScottPlot'
  inputs:
    command: 'build'
    projects: 'src/ScottPlot/ScottPlot.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build ScottPlot.Demo'
  inputs:
    command: 'build'
    projects: 'src/ScottPlot.Demo/ScottPlot.Demo.csproj'

### BUILD AND RUN PRIMARY TESTS
- task: DotNetCoreCLI@2
  displayName: 'Build Tests'
  inputs:
    command: 'build'
    projects: 'tests/ScottPlotTests.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: test
    projects: 'tests/ScottPlotTests.csproj'

### PUBLISH TEST OUTPUT AS AN ARTIFACT
- task: PublishPipelineArtifact@1
  displayName: 'Publish Tests (Windows)'
  condition: contains(variables['agent.os'], 'Windows')
  inputs:
    targetPath: tests/bin/Debug/netcoreapp2.0/artifacts
    artifactName: Sample Plot (Windows)
    
- task: PublishPipelineArtifact@1
  displayName: 'Publish Tests (MacOS)'
  condition: contains(variables['agent.os'], 'Darwin')
  inputs:
    targetPath: tests/bin/Debug/netcoreapp2.0/artifacts
    artifactName: Sample Plot (MacOS)
    
- task: PublishPipelineArtifact@1
  displayName: 'Publish Tests (Linux)'
  condition: contains(variables['agent.os'], 'Linux')
  inputs:
    targetPath: tests/bin/Debug/netcoreapp2.0/artifacts
    artifactName: Sample Plot (Linux)

### BUILD AND PACKAGE RELEASE (Windows only)
    
- task: VSBuild@1
  displayName: 'Build Release (Windows)'
  condition: contains(variables['agent.os'], 'Windows')
  inputs:
    solution: 'src/ScottPlotV4.sln'
    configuration: 'release'

- task: CopyFiles@2
  displayName: 'Copy Packages (Windows)'
  condition: contains(variables['agent.os'], 'Windows')
  inputs:
    Contents: |
      src/ScottPlot/bin/Release/*.nupkg
      src/ScottPlot/bin/Release/*.snupkg
      src/ScottPlot.WinForms/bin/Release/*.nupkg
      src/ScottPlot.WinForms/bin/Release/*.snupkg
      src/ScottPlot.WPF/bin/Release/*.nupkg
      src/ScottPlot.WPF/bin/Release/*.snupkg
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true

- task: PublishPipelineArtifact@1
  displayName: 'Publish Packages (Windows)'
  condition: contains(variables['agent.os'], 'Windows')
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifactName: NuGet Packages