# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

strategy:
  matrix:
    MacOS:
      imageName: 'macOS-latest'
    Linux:
      imageName: 'ubuntu-latest'
    Windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

variables:
  buildConfiguration: 'Release'

steps:

# install NuGet
- task: NuGetToolInstaller@0
  displayName: 'Install NuGet'

# automatically install packages noted in the solution
- task: NuGetCommand@2
  displayName: 'NuGet Restore Packages'
  inputs:
    restoreSolution: 'src/ScottPlotNoGUI.sln'

- task: DotNetCoreCLI@2
  displayName: 'NuGet install libgdiplus (for macOS)'
  inputs:
    command: 'custom'
    custom: 'add package'
    arguments: 'CoreCompat.libgdiplus'
    projects: |
     src/ScottPlot/ScottPlot.csproj 
     tests/ScottPlotTests.csproj

- task: DotNetCoreCLI@2
  displayName: 'Build ScottPlot'
  inputs:
    packageType: 'sdk'
    command: 'build'
    projects: |
     src/ScottPlot/ScottPlot.csproj 
     tests/ScottPlotTests.csproj

- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: test
    projects: 'tests/ScottPlotTests.csproj'

# Build the entire solution (user controls and demos) - WINDOWS ONLY
#- task: NuGetCommand@2
#  inputs:
#    restoreSolution: '$(solution)'
#
#- task: VSBuild@1
#  inputs:
#    solution: '$(solution)'
#    configuration: '$(buildConfiguration)'
