trigger:
- master

strategy:
  matrix:
    MacOS:
      imageName: 'macOS-latest'
      buildType: 'limited'
    Linux:
      imageName: 'ubuntu-latest'
      buildType: 'limited'
    Windows:
      imageName: 'windows-latest'
      buildType: 'full'

pool:
  vmImage: $(imageName)

variables:
  buildConfiguration: 'Release'

steps:

### INSTALL NUGET
- task: NuGetToolInstaller@0
  displayName: 'Install NuGet'

### RESTORE ALL PACKAGES IN SOLUTION
- task: NuGetCommand@2
  displayName: 'Restore all packages'
  inputs:
    restoreSolution: 'src/ScottPlot.sln'
    
### LIMITED BUILD ON LINUX/MAC
- task: DotNetCoreCLI@2
  displayName: 'Limited build'
  condition: eq('$(buildType)', 'limited')
  inputs:
    command: 'build'
    projects: 'src/ScottPlotNoGUI.sln'

### FULL BUILD ON WINDOWS    
- task: VSBuild@1
  displayName: 'Full build'
  condition: eq('$(buildType)', 'full')
  inputs:
    projects: 'src/ScottPlot.sln'
    
### RUN TESTS
- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: test
    projects: 'tests/ScottPlotTests.csproj'
