# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
      solution: 'src/ScottPlotNoGUI.sln'
    windows:
      imageName: 'windows-latest'
      solution: 'src/ScottPlot.sln'

pool:
  vmImage: $(imageName)

variables:
  buildConfiguration: 'Release'

steps:

- task: NuGetToolInstaller@0
  displayName: 'Install NuGet'

- task: NuGetCommand@2
  displayName: 'Install NuGet Packages'
  inputs:
    restoreSolution: 'src/ScottPlotNoGUI.sln'

- task: DotNetCoreCLI@2
  displayName: 'Build ScottPlot'
  inputs:
    packageType: 'sdk'
    command: 'build'
    projects: |
     src/ScottPlot/ScottPlot.csproj 
     tests/ScottPlotTests.csproj

- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: test
    projects: 'tests/ScottPlotTests.csproj'

# Build the entire solution (user controls and demos) - WINDOWS ONLY
#- task: NuGetCommand@2
#  inputs:
#    restoreSolution: '$(solution)'
#
#- task: VSBuild@1
#  inputs:
#    solution: '$(solution)'
#    configuration: '$(buildConfiguration)'
