trigger:
- master

strategy:
  matrix:
    MacOS:
      imageName: 'macOS-latest'
      solution: 'src/ScottPlotNoGUI.sln'
    Linux:
      imageName: 'ubuntu-latest'
      solution: 'src/ScottPlotNoGUI.sln'
    Windows:
      imageName: 'windows-latest'
      solution: 'src/ScottPlot.sln'

pool:
  vmImage: $(imageName)

variables:
  buildConfiguration: 'Release'

steps:

- task: NuGetToolInstaller@0
  displayName: 'Install NuGet'
    
- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    restoreSolution: '$(solution)'
    
- task: VSBuild@1
  condition: contains(variables['agent.os'], 'Windows')
  displayName: 'Build for Windows'
  inputs:
    projects: '$(solution)'
    platform: 'Any CPU'
    configuration: 'Release'
    
- task: DotNetCoreCLI@2
  condition: or(contains(variables['agent.os'], 'Mac'), contains(variables['agent.os'], 'Linux'))
  displayName: 'Build for Linux/MacOS'
  inputs:
    command: 'build'
    projects: '$(solution)'
  
- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: test
    projects: '$(solution)'
