trigger:
- master

strategy:
  matrix:
    FormatChecker:
      taskList: 'fail if autoformat was not run'
      imageName: 'ubuntu-latest'
    MacOS:
      taskList: 'build library, run tests'
      imageName: 'macOS-latest'
    Linux:
      taskList: 'build library, run tests'
      imageName: 'ubuntu-latest'
    Windows:
      taskList: 'build library, run tests, build solution'
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:

### FAIL THE BUILD IF THE AUTOFORMATTER WAS NOT RUN

- task: UseDotNet@2
  displayName: 'Acquire .NET Core 3'
  condition: contains(variables['taskList'], 'autoformat')
  inputs:
    packageType: 'sdk'
    version: '3.x'

- task: DotNetCoreCLI@2
  displayName: 'Install dotnet-format'
  condition: contains(variables['taskList'], 'autoformat')
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'update -g dotnet-format'

- task: DotNetCoreCLI@2
  displayName: 'Check Formatting'
  condition: contains(variables['taskList'], 'autoformat')
  inputs:
    command: 'custom'
    custom: 'format'
    arguments: '-w src/ScottPlotV4.sln --dry-run --check --verbosity diagnostic'

### INSTALL NUGET AND RESTORE PACKAGES

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'
  condition: contains(variables['taskList'], 'build')

- task: NuGetCommand@2
  displayName: 'Restore packages'
  condition: contains(variables['taskList'], 'build')
  inputs:
    restoreSolution: 'src/ScottPlotV4.sln'

### BUILD THE CORE SCOTTPLOT AND AND DEMO PROJECTS

- task: DotNetCoreCLI@2
  displayName: 'Build ScottPlot'
  condition: contains(variables['taskList'], 'build')
  inputs:
    command: 'build'
    projects: 'src/ScottPlot/ScottPlot.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build ScottPlot.Demo'
  condition: contains(variables['taskList'], 'build')
  inputs:
    command: 'build'
    projects: 'src/ScottPlot.Demo/ScottPlot.Demo.csproj'

### BUILD AND RUN TESTS

- task: DotNetCoreCLI@2
  displayName: 'Build Tests'
  condition: contains(variables['taskList'], 'test')
  inputs:
    command: 'build'
    projects: 'tests/ScottPlotTests.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  condition: contains(variables['taskList'], 'test')
  inputs:
    command: test
    projects: 'tests/ScottPlotTests.csproj'

### BUILD RELEASE OF FULL SOLUTION (Windows only)
    
- task: VSBuild@1
  displayName: 'Build Release (Windows)'
  condition: contains(variables['taskList'], 'solution')
  inputs:
    solution: 'src/ScottPlotV4.sln'
    configuration: 'release'