# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
      solution: 'src/ScottPlotNoGUI.sln'
    mac:
      imageName: 'macOS-latest'
      solution: 'src/ScottPlotNoGUI.sln'
    windows:
      imageName: 'windows-latest'
      solution: 'src/ScottPlot.sln'

pool:
  vmImage: $(imageName)

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk

- task: NuGetToolInstaller

- task: NuGetCommand
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI
  inputs:
    command: test
    projects: 'tests/ScottPlotTests.csproj'
    arguments: '--configuration $(buildConfiguration)'