# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

strategy:
  matrix:
    MacOS:
      imageName: 'macOS-latest'
      solution: 'src/ScottPlotNoGUI.sln'
    Linux:
      imageName: 'ubuntu-latest'
      solution: 'src/ScottPlotNoGUI.sln'
    Windows:
      imageName: 'windows-latest'
      solution: 'src/ScottPlot.sln'

pool:
  vmImage: $(imageName)

variables:
  buildConfiguration: 'Release'

steps:

- task: NuGetToolInstaller@0
  displayName: 'Install NuGet'
    
- task: NuGetCommand@2
  displayName: 'Install NuGet Packages'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build $(solution)'
  inputs:
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Test $(solution)'
  inputs:
    command: test
    projects: 'tests/ScottPlotTests.csproj'
