# This action runs 'dotnet format' and pushes the formatted code back to the main branch.
# Run 'dotnet format' in a project or solution folder to autoformat the code.
# The 'dotnet format' command requires Windows because ScottPlot 4 requires MSBuild.

name: Autoformat Fix

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**

jobs:
  check-format:
    name: Run 'dotnet format'
    runs-on: windows-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: ✨ Set up .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7"
      - name: ✍️ Fix ScottPlot4 formatting
        run: dotnet format "src/ScottPlot4/ScottPlot4.sln"
      - name: ✍️ Fix ScottPlot5 formatting
        run: dotnet format "src/ScottPlot5/ScottPlot5.sln"
      - name: 🚀 Push Changes
        run: |
          git config --global user.name 'Scott W Harden (via GitHub Actions)'
          git config --global user.email 'swharden@gmail.com'
          git commit -am "CI: autoformat"
          git push
