# This action uses 'dotnet format' to evaluate or fix source code
# based on the rules described in .editorconfig the file.
#
# The 'dotnet format' command can only be run at the solution level
# on Windows platforms because ScottPlot4 has Windows-only
# .NET Framework projects that can only be built with MSBuild on Windows.
#
# If this action is invoked by a commit to the main branch,
# it will autoformat the code and apply the changes as a new commit.

name: Autoformat

on:
  workflow_dispatch: # allow running manually
  pull_request: # run on all PR actions (push, open, reopen)
  push: # run whenever the main branch is modified (via a PR merge or direct committing)
    branches:
      - main
    paths:
      - src/**

env:
  SLN_SP4_FULL: "src/ScottPlot4/ScottPlot4.sln"
  SLN_SP5_FULL: "src/ScottPlot5/ScottPlot5.sln"
  DOTNET_VERSION: "7.0.x"

jobs:
  check-format:
    name: Autoformat
    runs-on: windows-latest
    steps:
      - name: 🛒 Checkout (PR)
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v3

      - name: 🛒 Checkout (main)
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: ✨ Set up .NET ${{env.DOTNET_VERSION}}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: ✒️ Check ScottPlot4 formatting
        if: github.event_name == 'pull_request'
        run: dotnet format --verify-no-changes ${{env.SLN_SP4_FULL}}
      - name: ✒️ Check ScottPlot5 formatting
        if: github.event_name == 'pull_request'
        run: dotnet format --verify-no-changes ${{env.SLN_SP5_FULL}}

      - name: ✍️ Fix ScottPlot4 formatting
        if: github.event_name != 'pull_request'
        run: dotnet format ${{env.SLN_SP4_FULL}}
      - name: ✍️ Fix ScottPlot5 formatting
        if: github.event_name != 'pull_request'
        run: dotnet format ${{env.SLN_SP5_FULL}}

      - name: 🚀 Push format changes
        if: github.event_name != 'pull_request'
        run: |
          git config --global user.name 'Scott W Harden (via GitHub Actions)'
          git config --global user.email 'swharden@gmail.com'
          git commit -am "CI: autoformat"
          git push
