# This action uses 'dotnet format' and FAILS if the code is not already formatted.
# Run 'dotnet format' in a project or solution folder to autoformat the code.
# The 'dotnet format' command requires Windows because ScottPlot 4 requires MSBuild.

on:
  workflow_dispatch:
  pull_request:

jobs:
  check-format:
    name: Autoformat
    runs-on: windows-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3
      - name: ✨ Set up .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7"
      - name: ✒️ Check ScottPlot4 formatting
        run: dotnet format --verify-no-changes "src/ScottPlot4/ScottPlot4.sln"
      - name: ✒️ Check ScottPlot5 formatting
        run: dotnet format --verify-no-changes "src/ScottPlot5/ScottPlot5.sln"
      - name: 💡 Post 'dotnet format' message
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GH_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '💡 This automated message is to remind contributors that the `dotnet format` command should be run to ensure the code modified by pull requests is formatted consistently with the rest of the code base. See `CONTRIBUTING.md` for additional information.'
            })
