name: Changelog

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - CHANGELOG.md

jobs:
  update:
    runs-on: windows-latest
    name: Update Changelog Webpage
    steps:
      - name: 🚀 Trigger Remote Workflow
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/ScottPlot/ScottPlot.NET/actions/workflows/changelog.yaml/dispatches
            -d '{"ref":"main"}'
