name: Changelog

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - CHANGELOG.md

jobs:
  update:
    runs-on: windows-latest
    name: Update Changelog Webpage
    steps:
      - name: 🚀 Trigger Remote Workflow
        run: |
          curl -L -X POST https://api.github.com/repos/ScottPlot/ScottPlot.NET/actions/workflows/changelog.yaml/dispatches -d '{"ref":"main"}' -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}"
