name: Test ScottPlot v5

on:
  workflow_dispatch:
  push:
    paths:
      - "src/ScottPlot5/**"
  pull_request:
    paths:
      - "src/ScottPlot5/**"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            osName: Linux
          - os: windows-latest
            osName: Windows
          - os: macos-latest
            osName: MacOS
    runs-on: ${{ matrix.os }}
    name: 🧪 Test on ${{ matrix.osName }}
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2
      - name: ✨ Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      - name: 🚚 Restore
        run: dotnet restore ./src/ScottPlot5/ScottPlot5.Tests
      - name: 🛠️ Build
        run: dotnet build ./src/ScottPlot5/ScottPlot5.Tests --configuration Release --no-restore
      - name: 🧪 Test
        run: dotnet test ./src/ScottPlot5/ScottPlot5.Tests --configuration Release --no-restore --verbosity normal
  solution:
    runs-on: windows-latest
    name: 🛠️ Build Solution
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2
      - name: ✨ Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      - name: 🚚 Restore
        run: dotnet restore ./src/ScottPlot5/
      - name: 🛠️ Build
        run: dotnet build ./src/ScottPlot5/ --configuration Release --no-restore
