name: Test ScottPlot Common

on:
  workflow_dispatch:
  push:
    paths:
      - "src/Common/**"
  pull_request:
    paths:
      - "src/Common/**"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2
      - name: ✨ Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      - name: 🚚 Restore
        run: dotnet restore ./src/Common/
      - name: 🛠️ Build
        run: dotnet build ./src/Common/ --configuration Release --no-restore
      - name: 🧪 Test
        run: dotnet test ./src/Common/ --configuration Release --no-restore --verbosity normal
