name: ScottPlot 5 CI

on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3
      - name: ✨ Setup .NET 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"
      - name: 🚚 Restore
        run: |
          dotnet restore "src/ScottPlot5/ScottPlot5 Tests"
          dotnet restore "src/ScottPlot5/ScottPlot5 Cookbook"
      - name: 🛠️ Build
        run: |
          dotnet build "src/ScottPlot5/ScottPlot5 Tests" --configuration Release --no-restore
          dotnet build "src/ScottPlot5/ScottPlot5 Cookbook" --configuration Release --no-restore
      - name: 🧪 Test
        run: dotnet test "src/ScottPlot5/ScottPlot5 Tests" --no-restore --verbosity minimal
      - name: 🧑‍🍳 Cookbook
        run: dotnet test "src/ScottPlot5/ScottPlot5 Cookbook" --no-restore --verbosity minimal

  windows:
    runs-on: windows-latest
    name: Full Build
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3
      - name: 🐢 Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: ✨ Setup .NET 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"
      - name: 🚚 Restore
        run: dotnet restore "src/ScottPlot5"
      - name: 🛠️ Build
        run: dotnet build "src/ScottPlot5" --configuration Release --no-restore
      - name: 📦 Pack
        run: |
          dotnet pack "src/ScottPlot5/ScottPlot5" --configuration Release
          dotnet pack "src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms" --configuration Release
          dotnet pack "src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF" --configuration Release
          dotnet pack "src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Avalonia" --configuration Release
          dotnet pack "src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Eto" --configuration Release
          dotnet pack "src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinUI" --configuration Release
      - name: 🧪 Test
        run: dotnet test "src/ScottPlot5" --no-restore --verbosity minimal
