name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "0 0 * * *"

jobs:
  rebuildWindows:
    runs-on: windows-latest
    name: Build Solution
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2
      - name: 🐢 Set up MSBuild
        uses: microsoft/setup-msbuild@v1.0.3
      - name: 🚚 Restore
        working-directory: src
        run: dotnet restore
      - name: 🐌 MSBuild
        working-directory: src
        run: msbuild -property:Configuration=Release -verbosity:minimal

  checkFormat:
    runs-on: ubuntu-latest
    name: Check Formatting
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2
      - name: ✨ Set up .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: ✒️ Set up dotnet-format
        run: dotnet tool install -g dotnet-format
      - name: 🧐 Check Code Format
        working-directory: src
        run: dotnet-format --check

  testLinux:
    runs-on: ubuntu-latest
    name: Test on Linux
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2
      - name: ✨ Set up .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: 🚚 Restore
        working-directory: src/tests
        run: dotnet restore
      - name: 🛠️ Build
        working-directory: src/tests
        run: dotnet build --configuration Release --no-restore
      - name: 🧪 Test
        working-directory: src/tests
        run: dotnet test --no-restore

  testWindows:
    runs-on: windows-latest
    name: Test on Windows
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2
      - name: ✨ Set up .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: 🚚 Restore
        working-directory: src/tests
        run: dotnet restore
      - name: 🛠️ Build
        working-directory: src/tests
        run: dotnet build --configuration Release --no-restore
      - name: 🧪 Test
        working-directory: src/tests
        run: dotnet test --no-restore

  testMacOS:
    runs-on: macos-latest
    name: Test on MacOS
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2
      - name: ✨ Set up .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: 🚚 Restore
        working-directory: src/tests
        run: dotnet restore
      - name: 🛠️ Build
        working-directory: src/tests
        run: dotnet build --configuration Release --no-restore
      - name: 🧪 Test
        working-directory: src/tests
        run: dotnet test --no-restore
