name: ScottPlot5

on:
  workflow_dispatch:
  push: # only runs on commits to main branch (typically after a merge)
    branches:
      - main
    paths:
      - "src/ScottPlot5/ScottPlot5 Cookbook/**"
  pull_request: # ⚠️⚠️⚠️ DELETE THIS ONCE THE CI SYSTEM IS FUNCTIONING PROPERLY ⚠️⚠️⚠️

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  publish:
    name: Cookbook
    runs-on: ubuntu-latest
    environment:
      name: Cookbook
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2
      - name: ✨ Set up .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: 🚚 Restore
        run: dotnet restore "src/ScottPlot5/ScottPlot5 Cookbook"
      - name: 🛠️ Build
        run: dotnet build "src/ScottPlot5/ScottPlot5 Cookbook" --no-restore
      - name: 🧑‍🍳 Generate Cookbook
        run: dotnet test "src/ScottPlot5/ScottPlot5 Cookbook" --no-restore --verbosity minimal

      - name: 🛠️ Configure Pages
        uses: actions/configure-pages@v2
      - name: 📦 Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dev/www"
      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
