name: Create code diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          output_file: "dev/code-diagram.svg"
          excluded_paths: "ignore,docfx,.github"
