name: Demo

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types:
      - created

jobs:
  winforms-demo:
    name: WinForms Demo
    runs-on: windows-latest
    env:
      CSPROJ_FOLDER: src/demo/ScottPlot.Demo.WinForms
      ZIP_FILENAME: ScottPlot-Demo-WinForms.zip

    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2

      - name: 🐢 Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.3

      - name: 🚚 Restore
        working-directory: ${{ env.CSPROJ_FOLDER }}
        run: dotnet restore

      - name: 🐌 MSBuild
        working-directory: ${{ env.CSPROJ_FOLDER }}
        run: msbuild -property:Configuration=Release -verbosity:minimal

      - name: 📦 Zip
        uses: thedoctor0/zip-release@4fb9e4ff72847dd3d1c111cf63834e353ed7cb3d # v0.6.0
        with:
          type: "zip"
          directory: "${{ env.CSPROJ_FOLDER }}/bin/Release"
          filename: "${{ env.ZIP_FILENAME }}"
          path: "."

      # - name: 💾 Store
      #   uses: actions/upload-artifact@v2
      #   with:
      #     retention-days: 1
      #     path: ${{ env.CSPROJ_FOLDER }}/bin/Release/${{ env.ZIP_FILENAME }}

      - name: 🚀 Upload
        uses: bayssmekanique/action-simple-file-upload@6a5813e1d0efe83cb6101cbba69ca59d3aed90b3
        with:
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          host: scottplot.net
          src: ${{ env.CSPROJ_FOLDER }}/bin/Release/${{ env.ZIP_FILENAME }}
          dest: /scottplot.net/public_html/demo/${{ env.ZIP_FILENAME }}

  wpf-demo:
    name: WPF Demo
    runs-on: windows-latest
    env:
      CSPROJ_FOLDER: src/demo/ScottPlot.Demo.WPF
      ZIP_FILENAME: ScottPlot-Demo-WPF.zip

    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2

      - name: 🐢 Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.3

      - name: 🚚 Restore
        working-directory: ${{ env.CSPROJ_FOLDER }}
        run: dotnet restore

      - name: 🐌 MSBuild
        working-directory: ${{ env.CSPROJ_FOLDER }}
        run: msbuild -property:Configuration=Release -verbosity:minimal

      - name: 📦 Zip
        uses: thedoctor0/zip-release@4fb9e4ff72847dd3d1c111cf63834e353ed7cb3d # v0.6.0
        with:
          type: "zip"
          directory: "${{ env.CSPROJ_FOLDER }}/bin/Release"
          filename: "${{ env.ZIP_FILENAME }}"
          path: "."

      # - name: 💾 Store
      #   uses: actions/upload-artifact@v2
      #   with:
      #     retention-days: 1
      #     path: ${{ env.CSPROJ_FOLDER }}/bin/Release/${{ env.ZIP_FILENAME }}

      - name: 🚀 Upload
        uses: bayssmekanique/action-simple-file-upload@6a5813e1d0efe83cb6101cbba69ca59d3aed90b3
        with:
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          host: scottplot.net
          src: ${{ env.CSPROJ_FOLDER }}/bin/Release/${{ env.ZIP_FILENAME }}
          dest: /scottplot.net/public_html/demo/${{ env.ZIP_FILENAME }}

  avalonia-demo:
    name: Avalonia Demo
    runs-on: windows-latest
    env:
      CSPROJ_FOLDER: src/demo/ScottPlot.Demo.Avalonia
      ZIP_FILENAME: ScottPlot-Demo-Avalonia.zip

    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2

      - name: 🐢 Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.3

      - name: 🚚 Restore
        working-directory: ${{ env.CSPROJ_FOLDER }}
        run: dotnet restore

      - name: 🐌 MSBuild
        working-directory: ${{ env.CSPROJ_FOLDER }}
        run: msbuild -property:Configuration=Release -verbosity:minimal

      - name: 📦 Zip
        uses: thedoctor0/zip-release@4fb9e4ff72847dd3d1c111cf63834e353ed7cb3d # v0.6.0
        with:
          type: "zip"
          directory: "${{ env.CSPROJ_FOLDER }}/bin/Release"
          filename: "${{ env.ZIP_FILENAME }}"
          path: "."

      # - name: 💾 Store
      #   uses: actions/upload-artifact@v2
      #   with:
      #     retention-days: 1
      #     path: ${{ env.CSPROJ_FOLDER }}/bin/Release/${{ env.ZIP_FILENAME }}

      - name: 🚀 Upload
        uses: bayssmekanique/action-simple-file-upload@6a5813e1d0efe83cb6101cbba69ca59d3aed90b3
        with:
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          host: scottplot.net
          src: ${{ env.CSPROJ_FOLDER }}/bin/Release/${{ env.ZIP_FILENAME }}
          dest: /scottplot.net/public_html/demo/${{ env.ZIP_FILENAME }}
