name: Update Developer Website

on:
  workflow_dispatch:
  push: # run on pushes to main (only happens when PRs are merged or admin commits directly to main)
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  publish:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: Cookbook
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3
      - name: ✨ Setup .NET 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"
      - name: 🚚 Restore
        run: dotnet restore dev/CodeAnalysis
      - name: 🛠️ Build
        run: dotnet build dev/CodeAnalysis
      - name: 🔎 Analyze
        run: dotnet run --project dev/CodeAnalysis
      - name: 🛠️ Configure Pages
        uses: actions/configure-pages@v2
      - name: 📦 Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dev/www"
      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
