name: Update Developer Website

# This script copies contents of /dev/www to dev.scottplot.net (hosted by GitHub Pages)

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  publish:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: Cookbook
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3
      - name: 🛠️ Configure Pages
        uses: actions/configure-pages@v2
      - name: 📦 Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dev/www"
      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
