name: NuGet

on:
  workflow_dispatch:

jobs:
  publish:
    strategy:
      matrix:
        include:
          - dir: src/ScottPlot
            packageName: ScottPlot
          - dir: src/controls/ScottPlot.WinForms
            packageName: ScottPlot.WinForms
          - dir: src/controls/ScottPlot.WPF
            packageName: ScottPlot.WPF
          - dir: src/controls/ScottPlot.Avalonia
            packageName: ScottPlot.Avalonia
    runs-on: windows-latest
    name: Publish ${{ matrix.packageName }}
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2
      - name: 🐢 Set up MSBuild
        uses: microsoft/setup-msbuild@v1.0.3
      - name: 🚚 Restore
        working-directory: ${{ matrix.dir }}
        run: dotnet restore
      - name: 🐌 MSBuild
        working-directory: ${{ matrix.dir }}
        run: msbuild -property:Configuration=Release -verbosity:minimal
      - name: 🧪 Test
        working-directory: ${{ matrix.dir }}
        run: dotnet test --no-restore
      - name: 🚀 Publish
        working-directory: ${{ matrix.dir }}
        run: nuget push bin/Release/*.nupkg
