name: Publish NuGet Packages

on:
  workflow_dispatch:

jobs:
  publish:
    strategy:
      matrix:
        include:
          - projectDirectory: src/ScottPlot
            packageName: ScottPlot
          - projectDirectory: src/controls/ScottPlot.WinForms
            projectFileName: ScottPlot.csproj
            packageName: ScottPlot.WinForms
          - projectDirectory: src/controls/ScottPlot.WPF
            projectFileName: ScottPlot.WPF.NUGET.csproj
            packageName: ScottPlot.WPF
          - projectDirectory: src/controls/ScottPlot.Avalonia
            projectFileName: ScottPlot.Avalonia.NUGET.csproj
            packageName: ScottPlot.Avalonia
    runs-on: windows-latest
    name: ${{ matrix.packageName }}
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2
      - name: 🐢 Set up MSBuild
        uses: microsoft/setup-msbuild@v1.0.3
      - name: 🚚 Restore
        working-directory: ${{ matrix.projectDirectory }}
        run: dotnet restore ${{ matrix.projectFileName }}
      - name: 🐌 MSBuild
        working-directory: ${{ matrix.projectDirectory }}
        run: msbuild ${{ matrix.projectFileName }} -property:Configuration=Release -verbosity:minimal
      - name: 🚀 Publish
        working-directory: ${{ matrix.projectDirectory }}
        run: nuget push bin/Release/*.nupkg
