name: NuGet

on:
  workflow_dispatch:

jobs:
  publish:
    strategy:
      matrix:
        include:
          - dir: src/ScottPlot
            packageName: ScottPlot
          - dir: src/controls/ScottPlot.WinForms
            packageName: ScottPlot.WinForms
          - dir: src/controls/ScottPlot.WPF
            packageName: ScottPlot.WPF
          - dir: src/controls/ScottPlot.Avalonia
            packageName: ScottPlot.Avalonia

    runs-on: ubuntu-latest
    name: Publish ${{ matrix.packageName }}
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2
      - name: ✨ Set up .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: 🚚 Restore
        working-directory: ${{ matrix.dir }}
        run: dotnet restore
      - name: 🛠️ Build
        working-directory: ${{ matrix.dir }}
        run: dotnet build --configuration Release --no-restore
      - name: 🧪 Test
        working-directory: ${{ matrix.dir }}
        run: dotnet test --no-restore
      - name: 🚀 Publish
        working-directory: ${{ matrix.dir }}
        run: nuget push bin/Release/*.nupkg
