name: Publish on NuGet

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: windows-latest
    name: Build and Publish
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2
      - name: 🐢 Set up MSBuild
        uses: microsoft/setup-msbuild@v1.0.3
      - name: ✨ Set up .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: 🚚 Restore
        working-directory: src
        run: dotnet restore
      - name: 📦 ScottPlot
        run: dotnet pack src/ScottPlot/ScottPlot.csproj --configuration Release
      - name: 📦 ScottPlot.WinForms
        run: dotnet pack src/controls/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj --configuration Release
      - name: 📦 ScottPlot.WPF
        run: dotnet pack src/controls/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj --configuration Release
      - name: 📦 ScottPlot.Avalonia
        # Avalonia control requires package to be made at build time
        run: dotnet build src/controls/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj --configuration Release
      - name: 🚀 Publish Packages
        run: |
          nuget push src/ScottPlot/bin/Release/*.nupkg --skip-duplicate
          nuget push src/controls/ScottPlot.WinForms/bin/Release/*.nupkg --skip-duplicate
          nuget push src/controls/ScottPlot.WPF/bin/Release/*.nupkg --skip-duplicate
          nuget push src/controls/ScottPlot.Avalonia/bin/Release/*.nupkg --skip-duplicate
