name: Publish on NuGet

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    name: Build and Publish
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2
      - name: 🐢 Set up MSBuild
        uses: microsoft/setup-msbuild@v1.0.3
      - name: ✨ Set up .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: 🚚 Restore
        working-directory: src
        run: dotnet restore
      - name: 🛠️ Build
        run: |
          dotnet build src/ScottPlot/ScottPlot.csproj --verbosity quiet --configuration Release
          dotnet build src/controls/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj --verbosity quiet --configuration Release
          dotnet build src/controls/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj --verbosity quiet --configuration Release
          dotnet build src/controls/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj --verbosity quiet --configuration Release
      - name: 🚀 Publish
        run: |
          nuget push src/ScottPlot/bin/Release/*.nupkg
          nuget push src/controls/ScottPlot.WinForms/bin/Release/*.nupkg
          nuget push src/controls/ScottPlot.WPF/bin/Release/*.nupkg
          nuget push src/controls/ScottPlot.Avalonia/bin/Release/*.nupkg
