name: Publish on NuGet

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    name: Build and Publish
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2
      - name: 🐢 Set up MSBuild
        uses: microsoft/setup-msbuild@v1.0.3
      - name: ✨ Set up .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: 🚚 Restore
        working-directory: src
        run: dotnet restore
      - name: 📦 Pack ScottPlot
        run: dotnet pack src/ScottPlot/ScottPlot.csproj --output packages --configuration Release
      - name: 📦 Pack ScottPlot.WinForms
        run: dotnet pack src/controls/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj --output packages --configuration Release
      - name: 📦 Pack ScottPlot.WPF
        run: dotnet pack src/controls/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj --output packages --configuration Release
      - name: 📦 Pack ScottPlot.Avalonia
        run: dotnet pack src/controls/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj --output packages --configuration Release
      - name: 🚀 Publish
        run: nuget push packages/*.nupkg
