name: ScottPlot 5 Deploy

on:
  workflow_dispatch:

jobs:
  windows:
    name: 🚀 Publish ScottPlot5 Packages
    runs-on: windows-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3

      - name: ✨ Setup .NET 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: 🛠️ Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}

      - name: 📦 Package ScottPlot
        working-directory: "src/ScottPlot5/ScottPlot5"
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet pack --configuration Release
          nuget push \bin\Release\*.nupkg -SkipDuplicate -Source https://api.nuget.org/v3/index.json

      - name: 📦 Package ScottPlot.WinForms
        working-directory: "src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms"
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet pack --configuration Release
          nuget push \bin\Release\*.nupkg -SkipDuplicate -Source https://api.nuget.org/v3/index.json

      - name: 📦 Package ScottPlot.WPF
        working-directory: "src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF"
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet pack --configuration Release
          nuget push \bin\Release\*.nupkg -SkipDuplicate -Source https://api.nuget.org/v3/index.json

      - name: 📦 Package ScottPlot.Avalonia
        working-directory: "src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Avalonia"
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet pack --configuration Release
          nuget push \bin\Release\*.nupkg -SkipDuplicate -Source https://api.nuget.org/v3/index.json

      - name: 📦 Package ScottPlot.Eto
        working-directory: "src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Eto"
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet pack --configuration Release
          nuget push \bin\Release\*.nupkg -SkipDuplicate -Source https://api.nuget.org/v3/index.json

      - name: 📦 Package ScottPlot.WinUI
        working-directory: "src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinUI"
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet pack --configuration Release
          nuget push \bin\Release\*.nupkg -SkipDuplicate -Source https://api.nuget.org/v3/index.json
