name: ScottPlot 4 Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: 🚀 Publish ScottPlot4 Packages
    runs-on: windows-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3

      - name: ✨ Setup .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: 🛠️ Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}

      - name: 🚀 Deploy ScottPlot
        run: |
          dotnet restore src/ScottPlot4/ScottPlot/ScottPlot.csproj
          dotnet build src/ScottPlot4/ScottPlot/ScottPlot.csproj --configuration Release
          dotnet pack src/ScottPlot4/ScottPlot/ScottPlot.csproj --configuration Release
          nuget push "src\ScottPlot4\ScottPlot\bin\Release\*.nupkg" -SkipDuplicate -Source https://api.nuget.org/v3/index.json

      - name: 🚀 Deploy ScottPlot.WinForms
        run: |
          dotnet restore src/ScottPlot4/ScottPlot.WinForms
          dotnet build src/ScottPlot4/ScottPlot.WinForms --configuration Release
          dotnet pack src/ScottPlot4/ScottPlot.WinForms --configuration Release
          nuget push "src\ScottPlot4\ScottPlot.WinForms\bin\Release\*.nupkg" -SkipDuplicate -Source https://api.nuget.org/v3/index.json

      - name: 🚀 Deploy ScottPlot.WPF
        run: |
          dotnet restore src/ScottPlot4/ScottPlot.WPF
          dotnet build src/ScottPlot4/ScottPlot.WPF --configuration Release
          dotnet pack src/ScottPlot4/ScottPlot.WPF --configuration Release
          nuget push "src\ScottPlot4\ScottPlot.WPF\bin\Release\*.nupkg" -SkipDuplicate -Source https://api.nuget.org/v3/index.json

      - name: 🚀 Deploy ScottPlot.Avalonia
        run: |
          dotnet restore src/ScottPlot4/ScottPlot.Avalonia
          dotnet build src/ScottPlot4/ScottPlot.Avalonia --configuration Release
          dotnet pack src/ScottPlot4/ScottPlot.Avalonia --configuration Release
          nuget push "src\ScottPlot4\ScottPlot.Avalonia\bin\Release\*.nupkg" -SkipDuplicate -Source https://api.nuget.org/v3/index.json

      - name: 🚀 Deploy ScottPlot.Eto
        run: |
          dotnet restore src/ScottPlot4/ScottPlot.Eto
          dotnet build src/ScottPlot4/ScottPlot.Eto --configuration Release
          dotnet pack src/ScottPlot4/ScottPlot.Eto --configuration Release
          nuget push "src\ScottPlot4\ScottPlot.Eto\bin\Release\*.nupkg" -SkipDuplicate -Source https://api.nuget.org/v3/index.json
