name: CodeQL

on:
  workflow_dispatch:

jobs:
  windows:
    name: Security Analysis
    runs-on: windows-latest
    permissions:
      security-events: write
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3
      - name: 🐢 Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: ✨ Setup .NET 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"
      - name: ⚙️ Setup CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: csharp
      - name: 🚚 Restore SP4
        run: dotnet restore "src/ScottPlot4"
      - name: 🛠️ Build SP4
        run: dotnet build "src/ScottPlot4"
      - name: 🚚 Restore SP5
        run: dotnet restore "src/ScottPlot5"
      - name: 🛠️ Build SP5
        run: dotnet build "src/ScottPlot5"
      - name: 🔐 Analyze
        uses: github/codeql-action/analyze@v2
