name: PR CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/ScottPlot5/**

env:
  SLN_SP5_TEST: "src/ScottPlot5/ScottPlot5-tests.slnf"
  SLN_SP5_FULL: "src/ScottPlot5/ScottPlot5.sln"
  DOTNET_VERSION: "7.0.x"

jobs:
  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3
      - name: ✨ Setup .NET ${{env.DOTNET_VERSION}}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}
      - name: 🚚 Restore
        run: dotnet restore ${{env.SLN_SP5_TEST}}
      - name: 🛠️ Build
        run: dotnet build ${{env.SLN_SP5_TEST}} --configuration Release --no-restore
      - name: 🧪 Test
        run: dotnet test ${{env.SLN_SP5_TEST}} --configuration Release --no-restore --verbosity minimal

  test-windows:
    name: Test on Windows
    runs-on: windows-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3
      - name: 🐢 Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: ✨ Setup .NET ${{env.DOTNET_VERSION}}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}
      - name: 🚚 Restore
        run: dotnet restore ${{env.SLN_SP5_FULL}}
      - name: 🛠️ Build
        run: dotnet build ${{env.SLN_SP5_FULL}} --configuration Release --no-restore
      - name: 🧪 Test
        run: dotnet test ${{env.SLN_SP5_FULL}} --configuration Release --no-restore --verbosity minimal
      - name: 📦 Package
        run: dotnet pack ${{env.SLN_SP4_TEST}} --configuration Release
